import Head from 'next/head'
import Image from 'next/image'
import HomeMain from '../components/HomeMain'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <HomeMain/>
    </div>
  )
}
