import Head from 'next/head'
import HomeMain from '../components/HomeMain'



export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>MAC2023 Homepage </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon2.png" />
      </Head>
  <HomeMain/>
    </div>
  )
}
